window.TRAINER_DATA={
vocab:[
["שלום","hello / peace","Basics"],["ספר","book","Basics"],["בית","house / home","Basics"],["תלמיד","student","Basics"],["מורה","teacher","Basics"],["קפה","coffee","Basics"],["מים","water","Basics"],["לחם","bread","Basics"],["חדש","new","Basics"],["טוב","good","Basics"],
["מי","who","Question words"],["מה","what","Question words"],["איפה","where","Question words"],["מאיפה","from where","Question words"],["כמה","how many / how much","Question words"],["מתי","when","Question words"],["למה","why","Question words"],["איך","how","Question words"],
["אני","I","Pronouns"],["אתה","you (m.s.)","Pronouns"],["את","you (f.s.)","Pronouns"],["הוא","he","Pronouns"],["היא","she","Pronouns"],["אנחנו","we","Pronouns"],["אתם","you (m.pl.)","Pronouns"],["אתן","you (f.pl.)","Pronouns"],["הם","they (m.)","Pronouns"],["הן","they (f.)","Pronouns"],
["ישראל","Israel","Places"],["ירושלים","Jerusalem","Places"],["תל אביב","Tel Aviv","Places"],["חיפה","Haifa","Places"],["באר שבע","Be'er Sheva","Places"],["אשדוד","Ashdod","Places"],["מצרים","Egypt","Places"],["לבנון","Lebanon","Places"],["סוריה","Syria","Places"],["ירדן","Jordan","Places"],
["צפון","north","Directions"],["דרום","south","Directions"],["מזרח","east","Directions"],["מערב","west","Directions"],
["אבא","father / dad","Family"],["אמא","mother / mom","Family"],["בן","son","Family"],["בת","daughter","Family"],["אח","brother","Family"],["אחות","sister","Family"],["ילדים","children","Family"],["משפחה","family","Family"],
["חדר","room","Home"],["שולחן","table","Home"],["כיסא","chair","Home"],["מיטה","bed","Home"],["חלון","window","Home"],["דלת","door","Home"],["מחשב","computer","Home"],["טלפון","telephone","Home"],["ספרים","books","Home"],
["רוצה","wants / want","Verbs"],["לומד","studies / learns","Verbs"],["עובד","works","Verbs"],["קורא","reads","Verbs"],["כותב","writes","Verbs"],["אוכל","eats","Verbs"],["שותה","drinks","Verbs"],["הולך","goes / walks","Verbs"],["נוסע","travels / rides","Verbs"],["קונה","buys","Verbs"],["רואה","sees","Verbs"],["עושה","does / makes","Verbs"],["גר","lives / resides","Verbs"],
["תמיד","always","Frequency"],["בדרך כלל","usually / generally","Frequency"],["לפעמים","sometimes","Frequency"],["אף פעם לא","never","Frequency"],
["יש","there is / there are","Grammar"],["אין","there isn't / there aren't","Grammar"],["של","of / belonging to","Grammar"],["שלי","mine / my","Grammar"],["שלך","yours / your","Grammar"],["שלו","his","Grammar"],["שלה","hers","Grammar"],["שלנו","ours / our","Grammar"],
["ברכה","blessing / greeting","Book B · Greetings"],["כרטיס ברכה","greeting card","Book B · Greetings"],["חג","holiday","Book B · Greetings"],["אושר","happiness","Book B · Greetings"],["זריחה","sunrise","Book B · Greetings"],["שקיעה","sunset","Book B · Greetings"],["מחשבה","thought","Book B · Greetings"],["משמעות","meaning / significance","Book B · Greetings"],["צורך","need","Book B · Greetings"],["געגועים","longing / missing someone","Book B · Greetings"],["ילדות","childhood","Book B · Greetings"],["מיתוס","myth","Book B · Reading"],
["סטודנט","student","Book B · Study"],["פרופסור","professor","Book B · Study"],["רפואה","medicine","Book B · Study"],["מבחן","exam / test","Book B · Study"],["אוניברסיטה","university","Book B · Study"],["ציון","grade / score","Book B · Study"],["דיאטה","diet","Book B · Health"],["ארוחה","meal","Book B · Health"],["מרפאה","clinic","Book B · Health"],["רופא","doctor","Book B · Health"],["בחור","young man","Book B · People"],["בחורה","young woman","Book B · People"],["חרוץ","diligent / hardworking","Book B · Adjectives"],["קצר","short","Book B · Adjectives"],["ארוך","long","Book B · Adjectives"],["קל","easy / light","Book B · Adjectives"],["קשה","difficult / hard","Book B · Adjectives"],["נחמד","nice / pleasant","Book B · Adjectives"],["בטוח","safe / sure","Book B · Adjectives"]
,
["גלויה","postcard","Teacher notes · Holidays"],["מנהג","custom","Teacher notes · Holidays"],["המצאה","invention","Teacher notes · Holidays"],["השפעה","influence","Teacher notes · Holidays"],["טלפון נייד","mobile phone","Teacher notes · Daily life"],["נפלא","wonderful","Teacher notes · Adjectives"],["זריחה","sunrise","Teacher notes · Time"],["שקיעה","sunset","Teacher notes · Time"],["חגיגה","celebration","Teacher notes · Holidays"],["תפילה","prayer","Teacher notes · Jewish life"],["אורח","guest","Teacher notes · People"],["לוח השנה","calendar","Teacher notes · Daily life"],["מיתוס","myth","Teacher notes · Reading"],["תרבות","culture","Teacher notes · Reading"],["מסורת","tradition","Teacher notes · Jewish life"],["טקס","ceremony","Teacher notes · Jewish life"],["חתונה","wedding","Teacher notes · Jewish life"],["מסוכן","dangerous","Teacher notes · Adjectives"],["געגוע","longing / nostalgia","Teacher notes · Feelings"],["אווירה","atmosphere","Teacher notes · Feelings"],["הרצאה","lecture","Teacher notes · Study"],["גיבור","hero","Teacher notes · Reading"],["חוכמה","wisdom","Teacher notes · Reading"],["התנהגות","behavior","Teacher notes · People"],["ערך","value","Teacher notes · Reading"],["שקט","quiet / silence","Teacher notes · Daily life"],["ממלכה","kingdom","Teacher notes · Reading"],["חבילה","package","Teacher notes · Daily life"],["הבטחה","promise","Teacher notes · Daily life"],["הפתעה","surprise","Teacher notes · Daily life"],["מאמר","article","Teacher notes · Study"],["חללית","spacecraft","Teacher notes · Reading"],["מאדים","Mars","Teacher notes · Reading"],["מחקר","research","Teacher notes · Study"],["חקירה","investigation","Teacher notes · Study"],["קיר","wall","Teacher notes · Home"],["קבוצה","team / group","Teacher notes · People"],["סכנה","danger","Teacher notes · Daily life"],["רעל","poison","Teacher notes · Daily life"],["כריכים","sandwiches","Teacher notes · Food"],["שטיח","rug / carpet","Teacher notes · Home"],["צעצועים","toys","Teacher notes · Home"],["כיור","sink","Teacher notes · Home"],["גדר","fence","Teacher notes · Places"],["מדרגות","stairs","Teacher notes · Places"],["מעלית","elevator","Teacher notes · Places"],["פינה","corner","Teacher notes · Places"],["שוער","goalkeeper","Teacher notes · Sports"],["כניסה","entrance","Teacher notes · Action nouns"],["יציאה","exit","Teacher notes · Action nouns"],["ירידה","descent / going down","Teacher notes · Action nouns"],["עלייה","ascent / going up","Teacher notes · Action nouns"],["כורסה","armchair","Teacher notes · Home"],["ספה","sofa","Teacher notes · Home"],["מנורה","lamp","Teacher notes · Home"],["מגרה","drawer","Teacher notes · Home"],["ברז","faucet","Teacher notes · Home"],["תנור","oven","Teacher notes · Home"],["תריס","shutter","Teacher notes · Home"],["וילון","curtain","Teacher notes · Home"],["אגרטל","vase","Teacher notes · Home"],["מדף","shelf","Teacher notes · Home"]
].map(function(x){return{he:x[0],en:x[1],cat:x[2]}}),
sentences:[
{en:"I live in Jerusalem.",he:"אני גר בירושלים"},
{en:"He drinks coffee.",he:"הוא שותה קפה"},
{en:"We study Hebrew.",he:"אנחנו לומדים עברית"},
{en:"There are books on the table.",he:"יש ספרים על השולחן"},
{en:"She works at home.",he:"היא עובדת בבית"},
{en:"They travel to Tel Aviv.",he:"הם נוסעים לתל אביב"},
{en:"The student reads a book.",he:"התלמיד קורא ספר"},
{en:"The teacher writes at the table.",he:"המורה כותב ליד השולחן"},
{en:"I drink water at home.",he:"אני שותה מים בבית"},
{en:"We travel to Haifa.",he:"אנחנו נוסעים לחיפה"},
{en:"She reads a new book.",he:"היא קוראת ספר חדש"},
{en:"He works in Jerusalem.",he:"הוא עובד בירושלים"},
{en:"The children are at home.",he:"הילדים בבית"},
{en:"There is coffee on the table.",he:"יש קפה על השולחן"},
{en:"I usually read at home.",he:"אני בדרך כלל קורא בבית"},
{en:"They sometimes drink coffee.",he:"הם לפעמים שותים קפה"},
{en:"We always study Hebrew.",he:"אנחנו תמיד לומדים עברית"},
{en:"She goes to Tel Aviv.",he:"היא הולכת לתל אביב"},
{en:"The student was afraid to fail the exams.",he:"הסטודנט פחד להיכשל במבחנים"},
{en:"The professor suggested that the student study another month.",he:"הפרופסור הציע לסטודנט שילמד עוד חודש"},
{en:"A nice doctor enters the large clinic.",he:"רופא נחמד נכנס למרפאה הגדולה"},
{en:"Dani succeeded on the easy exam.",he:"דני הצליח במבחן הקל"},
{en:"The student failed the difficult exam.",he:"התלמיד נכשל במבחן הקשה"},
{en:"Every day he used to go to the market.",he:"כל יום הוא היה הולך לשוק"},
{en:"Every year they used to send greeting cards.",he:"כל שנה הן היו שולחות כרטיסי ברכה"},
{en:"I was in the city and ate dinner at a restaurant.",he:"אני הייתי בעיר ואכלתי ארוחת ערב במסעדה"},
{en:"The student studies in order to succeed on the exam.",he:"הסטודנט לומד כדי להצליח במבחן"},
{en:"The young woman writes a greeting card for the holiday.",he:"הבחורה כותבת כרטיס ברכה לחג"},
{en:"The professor asks a question and the student answers.",he:"הפרופסור שואל שאלה והסטודנט עונה"}
,
{en:"I greet you for your birthday.",he:"אני מברך אותך ליום ההולדת שלך"},
{en:"Mom prepares a cake.",he:"אמא מכינה עוגה"},
{en:"You prepare homework.",he:"אתה מכין שיעורי בית"},
{en:"I miss Grandma.",he:"אני מתגעגע לסבתא"},
{en:"She hangs the picture on the wall.",he:"היא תולה את התמונה על הקיר"},
{en:"It is written on the calendar.",he:"זה כתוב בלוח השנה"},
{en:"They are very happy at the wedding.",he:"הם שמחים מאוד בחתונה"},
{en:"She throws the garbage into the bin.",he:"היא זורקת את האשפה לפח"},
{en:"She crosses the road at the crosswalk.",he:"היא חוצה את הכביש במעבר חצייה"},
{en:"I am going to sleep now so that in the morning I can get up early.",he:"אני הולך לישון עכשיו כדי שבבוקר אוכל לקום מוקדם"},
{en:"I bought a car so that I can travel.",he:"קניתי מכונית כדי שאוכל לנסוע"},
{en:"The students come to all the lessons so that they can understand the texts.",he:"התלמידים באים לכל השיעורים כדי שהם יוכלו להבין את הטקסטים"},
{en:"She serves meals in a restaurant.",he:"היא מגישה ארוחות במסעדה"},
{en:"The children fall asleep at eight in the evening.",he:"הילדים נרדמים בשמונה בערב"},
{en:"She washes dishes at home.",he:"היא שוטפת כלים בבית"}
],
verbs:[
{
infinitive:"לכתוב",actionNoun:"כתיבה",
present:{"אני":"כותב","אתה":"כותב","את":"כותבת","הוא":"כותב","היא":"כותבת","אנחנו":"כותבים","אתם":"כותבים","הם":"כותבים"},
past:{"אני":"כתבתי","אתה":"כתבת","את":"כתבת","הוא":"כתב","היא":"כתבה","אנחנו":"כתבנו","אתם":"כתבתם","הם":"כתבו"},
future:{"אני":"אכתוב","אתה":"תכתוב","את":"תכתבי","הוא":"יכתוב","היא":"תכתוב","אנחנו":"נכתוב","אתם":"תכתבו","הם":"יכתבו"}
},
{
infinitive:"לקרוא",actionNoun:"קריאה",
present:{"אני":"קורא","אתה":"קורא","את":"קוראת","הוא":"קורא","היא":"קוראת","אנחנו":"קוראים","אתם":"קוראים","הם":"קוראים"},
past:{"אני":"קראתי","אתה":"קראת","את":"קראת","הוא":"קרא","היא":"קראה","אנחנו":"קראנו","אתם":"קראתם","הם":"קראו"},
future:{"אני":"אקרא","אתה":"תקרא","את":"תקראי","הוא":"יקרא","היא":"תקרא","אנחנו":"נקרא","אתם":"תקראו","הם":"יקראו"}
},
{
infinitive:"לאכול",actionNoun:"אכילה",
present:{"אני":"אוכל","אתה":"אוכל","את":"אוכלת","הוא":"אוכל","היא":"אוכלת","אנחנו":"אוכלים","אתם":"אוכלים","הם":"אוכלים"},
past:{"אני":"אכלתי","אתה":"אכלת","את":"אכלת","הוא":"אכל","היא":"אכלה","אנחנו":"אכלנו","אתם":"אכלתם","הם":"אכלו"},
future:{"אני":"אוכל","אתה":"תאכל","את":"תאכלי","הוא":"יאכל","היא":"תאכל","אנחנו":"נאכל","אתם":"תאכלו","הם":"יאכלו"}
},
{
infinitive:"לשתות",actionNoun:"שתייה",
present:{"אני":"שותה","אתה":"שותה","את":"שותה","הוא":"שותה","היא":"שותה","אנחנו":"שותים","אתם":"שותים","הם":"שותים"},
past:{"אני":"שתיתי","אתה":"שתית","את":"שתית","הוא":"שתה","היא":"שתתה","אנחנו":"שתינו","אתם":"שתיתם","הם":"שתו"},
future:{"אני":"אשתה","אתה":"תשתה","את":"תשתי","הוא":"ישתה","היא":"תשתה","אנחנו":"נשתה","אתם":"תשתו","הם":"ישתו"}
},
{
infinitive:"ללכת",actionNoun:"הליכה",
present:{"אני":"הולך","אתה":"הולך","את":"הולכת","הוא":"הולך","היא":"הולכת","אנחנו":"הולכים","אתם":"הולכים","הם":"הולכים"},
past:{"אני":"הלכתי","אתה":"הלכת","את":"הלכת","הוא":"הלך","היא":"הלכה","אנחנו":"הלכנו","אתם":"הלכתם","הם":"הלכו"},
future:{"אני":"אלך","אתה":"תלך","את":"תלכי","הוא":"ילך","היא":"תלך","אנחנו":"נלך","אתם":"תלכו","הם":"ילכו"}
},
{
infinitive:"ללמוד",actionNoun:"למידה",
present:{"אני":"לומד","אתה":"לומד","את":"לומדת","הוא":"לומד","היא":"לומדת","אנחנו":"לומדים","אתם":"לומדים","הם":"לומדים"},
past:{"אני":"למדתי","אתה":"למדת","את":"למדת","הוא":"למד","היא":"למדה","אנחנו":"למדנו","אתם":"למדתם","הם":"למדו"},
future:{"אני":"אלמד","אתה":"תלמד","את":"תלמדי","הוא":"ילמד","היא":"תלמד","אנחנו":"נלמד","אתם":"תלמדו","הם":"ילמדו"}
},
{
infinitive:"לעבוד",actionNoun:"עבודה",
present:{"אני":"עובד","אתה":"עובד","את":"עובדת","הוא":"עובד","היא":"עובדת","אנחנו":"עובדים","אתם":"עובדים","הם":"עובדים"},
past:{"אני":"עבדתי","אתה":"עבדת","את":"עבדת","הוא":"עבד","היא":"עבדה","אנחנו":"עבדנו","אתם":"עבדתם","הם":"עבדו"},
future:{"אני":"אעבוד","אתה":"תעבוד","את":"תעבדי","הוא":"יעבוד","היא":"תעבוד","אנחנו":"נעבוד","אתם":"תעבדו","הם":"יעבדו"}
},
{
infinitive:"לגור",actionNoun:"מגורים",
present:{"אני":"גר","אתה":"גר","את":"גרה","הוא":"גר","היא":"גרה","אנחנו":"גרים","אתם":"גרים","הם":"גרים"},
past:{"אני":"גרתי","אתה":"גרת","את":"גרת","הוא":"גר","היא":"גרה","אנחנו":"גרנו","אתם":"גרתם","הם":"גרו"},
future:{"אני":"אגור","אתה":"תגור","את":"תגורי","הוא":"יגור","היא":"תגור","אנחנו":"נגור","אתם":"תגורו","הם":"יגורו"}
},
{
infinitive:"לנסוע",actionNoun:"נסיעה",
present:{"אני":"נוסע","אתה":"נוסע","את":"נוסעת","הוא":"נוסע","היא":"נוסעת","אנחנו":"נוסעים","אתם":"נוסעים","הם":"נוסעים"},
past:{"אני":"נסעתי","אתה":"נסעת","את":"נסעת","הוא":"נסע","היא":"נסעה","אנחנו":"נסענו","אתם":"נסעתם","הם":"נסעו"},
future:{"אני":"אסע","אתה":"תיסע","את":"תיסעי","הוא":"ייסע","היא":"תיסע","אנחנו":"ניסע","אתם":"תיסעו","הם":"ייסעו"}
},
{
infinitive:"לקנות",actionNoun:"קנייה",
present:{"אני":"קונה","אתה":"קונה","את":"קונה","הוא":"קונה","היא":"קונה","אנחנו":"קונים","אתם":"קונים","הם":"קונים"},
past:{"אני":"קניתי","אתה":"קנית","את":"קנית","הוא":"קנה","היא":"קנתה","אנחנו":"קנינו","אתם":"קניתם","הם":"קנו"},
future:{"אני":"אקנה","אתה":"תקנה","את":"תקני","הוא":"יקנה","היא":"תקנה","אנחנו":"נקנה","אתם":"תקנו","הם":"יקנו"}
},
{
infinitive:"לראות",actionNoun:"ראייה",
present:{"אני":"רואה","אתה":"רואה","את":"רואה","הוא":"רואה","היא":"רואה","אנחנו":"רואים","אתם":"רואים","הם":"רואים"},
past:{"אני":"ראיתי","אתה":"ראית","את":"ראית","הוא":"ראה","היא":"ראתה","אנחנו":"ראינו","אתם":"ראיתם","הם":"ראו"},
future:{"אני":"אראה","אתה":"תראה","את":"תראי","הוא":"יראה","היא":"תראה","אנחנו":"נראה","אתם":"תראו","הם":"יראו"}
},
{
infinitive:"לעשות",actionNoun:"עשייה",
present:{"אני":"עושה","אתה":"עושה","את":"עושה","הוא":"עושה","היא":"עושה","אנחנו":"עושים","אתם":"עושים","הם":"עושים"},
past:{"אני":"עשיתי","אתה":"עשית","את":"עשית","הוא":"עשה","היא":"עשתה","אנחנו":"עשינו","אתם":"עשיתם","הם":"עשו"},
future:{"אני":"אעשה","אתה":"תעשה","את":"תעשי","הוא":"יעשה","היא":"תעשה","אנחנו":"נעשה","אתם":"תעשו","הם":"יעשו"}
},
{
infinitive:"להיכנס",
present:{"אני":"נכנס","אתה":"נכנס","את":"נכנסת","הוא":"נכנס","היא":"נכנסת","אנחנו":"נכנסים","אתם":"נכנסים","הם":"נכנסים"},
past:{"אני":"נכנסתי","אתה":"נכנסת","את":"נכנסת","הוא":"נכנס","היא":"נכנסה","אנחנו":"נכנסנו","אתם":"נכנסתם","הם":"נכנסו"},
future:{"אני":"אכנס","אתה":"תיכנס","את":"תיכנסי","הוא":"ייכנס","היא":"תיכנס","אנחנו":"ניכנס","אתם":"תיכנסו","הם":"ייכנסו"}
},
{
infinitive:"לקום",
present:{"אני":"קם","אתה":"קם","את":"קמה","הוא":"קם","היא":"קמה","אנחנו":"קמים","אתם":"קמים","הם":"קמים"},
past:{"אני":"קמתי","אתה":"קמת","את":"קמת","הוא":"קם","היא":"קמה","אנחנו":"קמנו","אתם":"קמתם","הם":"קמו"},
future:{"אני":"אקום","אתה":"תקום","את":"תקומי","הוא":"יקום","היא":"תקום","אנחנו":"נקום","אתם":"תקומו","הם":"יקומו"}
},
{
infinitive:"לשלוח",
present:{"אני":"שולח","אתה":"שולח","את":"שולחת","הוא":"שולח","היא":"שולחת","אנחנו":"שולחים","אתם":"שולחים","הם":"שולחים"},
past:{"אני":"שלחתי","אתה":"שלחת","את":"שלחת","הוא":"שלח","היא":"שלחה","אנחנו":"שלחנו","אתם":"שלחתם","הם":"שלחו"},
future:{"אני":"אשלח","אתה":"תשלח","את":"תשלחי","הוא":"ישלח","היא":"תשלח","אנחנו":"נשלח","אתם":"תשלחו","הם":"ישלחו"}
},
{
infinitive:"לפתוח",
present:{"אני":"פותח","אתה":"פותח","את":"פותחת","הוא":"פותח","היא":"פותחת","אנחנו":"פותחים","אתם":"פותחים","הם":"פותחים"},
past:{"אני":"פתחתי","אתה":"פתחת","את":"פתחת","הוא":"פתח","היא":"פתחה","אנחנו":"פתחנו","אתם":"פתחתם","הם":"פתחו"},
future:{"אני":"אפתח","אתה":"תפתח","את":"תפתחי","הוא":"יפתח","היא":"תפתח","אנחנו":"נפתח","אתם":"תפתחו","הם":"יפתחו"}
},
{
infinitive:"לעבור",
present:{"אני":"עובר","אתה":"עובר","את":"עוברת","הוא":"עובר","היא":"עוברת","אנחנו":"עוברים","אתם":"עוברים","הם":"עוברים"},
past:{"אני":"עברתי","אתה":"עברת","את":"עברת","הוא":"עבר","היא":"עברה","אנחנו":"עברנו","אתם":"עברתם","הם":"עברו"},
future:{"אני":"אעבור","אתה":"תעבור","את":"תעברי","הוא":"יעבור","היא":"תעבור","אנחנו":"נעבור","אתם":"תעברו","הם":"יעברו"}
},
{
infinitive:"לשאול",
present:{"אני":"שואל","אתה":"שואל","את":"שואלת","הוא":"שואל","היא":"שואלת","אנחנו":"שואלים","אתם":"שואלים","הם":"שואלים"},
past:{"אני":"שאלתי","אתה":"שאלת","את":"שאלת","הוא":"שאל","היא":"שאלה","אנחנו":"שאלנו","אתם":"שאלתם","הם":"שאלו"},
future:{"אני":"אשאל","אתה":"תשאל","את":"תשאלי","הוא":"ישאל","היא":"תשאל","אנחנו":"נשאל","אתם":"תשאלו","הם":"ישאלו"}
},
{
infinitive:"לרצות",
present:{"אני":"רוצה","אתה":"רוצה","את":"רוצה","הוא":"רוצה","היא":"רוצה","אנחנו":"רוצים","אתם":"רוצים","הם":"רוצים"},
past:{"אני":"רציתי","אתה":"רצית","את":"רצית","הוא":"רצה","היא":"רצתה","אנחנו":"רצינו","אתם":"רציתם","הם":"רצו"},
future:{"אני":"ארצה","אתה":"תרצה","את":"תרצי","הוא":"ירצה","היא":"תרצה","אנחנו":"נרצה","אתם":"תרצו","הם":"ירצו"}
},
{
infinitive:"להצליח",actionNoun:"הצלחה",
present:{"אני":"מצליח","אתה":"מצליח","את":"מצליחה","הוא":"מצליח","היא":"מצליחה","אנחנו":"מצליחים","אתם":"מצליחים","הם":"מצליחים"},
past:{"אני":"הצלחתי","אתה":"הצלחת","את":"הצלחת","הוא":"הצליח","היא":"הצליחה","אנחנו":"הצלחנו","אתם":"הצלחתם","הם":"הצליחו"},
future:{"אני":"אצליח","אתה":"תצליח","את":"תצליחי","הוא":"יצליח","היא":"תצליח","אנחנו":"נצליח","אתם":"תצליחו","הם":"יצליחו"}
},
{
infinitive:"להיכשל",actionNoun:"כישלון",
present:{"אני":"נכשל","אתה":"נכשל","את":"נכשלת","הוא":"נכשל","היא":"נכשלת","אנחנו":"נכשלים","אתם":"נכשלים","הם":"נכשלים"},
past:{"אני":"נכשלתי","אתה":"נכשלת","את":"נכשלת","הוא":"נכשל","היא":"נכשלה","אנחנו":"נכשלנו","אתם":"נכשלתם","הם":"נכשלו"},
future:{"אני":"אכשל","אתה":"תיכשל","את":"תיכשלי","הוא":"ייכשל","היא":"תיכשל","אנחנו":"ניכשל","אתם":"תיכשלו","הם":"ייכשלו"}
}
],
connectors:[
{sentence:"אני שותה קפה ___ אני עייף.",answer:"כי",en:"I drink coffee because I am tired."},
{sentence:"אני עייף, ___ אני שותה קפה.",answer:"לכן",en:"I am tired, so I drink coffee."},
{sentence:"אני רוצה קפה ___ תה.",answer:"או",en:"I want coffee or tea."},
{sentence:"אני לומד עברית ___ אנגלית.",answer:"וגם",en:"I study Hebrew and also English."},
{sentence:"הוא עובד בבית, ___ היא עובדת במשרד.",answer:"אבל",en:"He works at home, but she works in an office."},
{sentence:"___ יש לי זמן, אני קורא ספר.",answer:"אם",en:"If I have time, I read a book."},
{sentence:"אם יש לי זמן, ___ אני קורא ספר.",answer:"אז",en:"If I have time, then I read a book."},
{sentence:"אני אוכל, ___ אני שותה קפה.",answer:"ואחר כך",en:"I eat, and afterward I drink coffee."},
{sentence:"___ הולך לעבודה, אני שותה קפה.",answer:"לפני שאני",en:"Before I go to work, I drink coffee."},
{sentence:"___ חוזר הביתה, אני קורא ספר.",answer:"אחרי שאני",en:"After I return home, I read a book."},
{sentence:"___ נוסע באוטובוס, אני קורא.",answer:"כשאני",en:"When I travel by bus, I read."},
{sentence:"אני לומד עברית ___ אני רוצה לקרוא ספרים.",answer:"כי",en:"I study Hebrew because I want to read books."},
{sentence:"היא גרה בחיפה, ___ היא עובדת בתל אביב.",answer:"אבל",en:"She lives in Haifa, but she works in Tel Aviv."},
{sentence:"___ אנחנו מסיימים ללמוד, אנחנו שותים קפה.",answer:"אחרי שאנחנו",en:"After we finish studying, we drink coffee."},
{sentence:"___ אנחנו מתחילים ללמוד, אנחנו קוראים.",answer:"לפני שאנחנו",en:"Before we begin studying, we read."},
{sentence:"___ אתה רוצה ללמוד, אתה צריך לקרוא.",answer:"אם",en:"If you want to study, you need to read."},
{sentence:"אני לומד כל יום ___ להצליח במבחן.",answer:"כדי",en:"I study every day in order to succeed on the exam."},
{sentence:"___ התקרבו המבחנים, הסטודנט התחיל לדאוג.",answer:"כאשר",en:"When the exams approached, the student began to worry."},
{sentence:"הוא רצה להיות רופא, ___ הוא פחד להיכשל.",answer:"אבל",en:"He wanted to be a doctor, but he was afraid to fail."},
{sentence:"אפשר ללמוד עוד חודש ___ לנסות שוב עכשיו.",answer:"או",en:"It is possible to study for another month or try again now."},
{sentence:"היא כתבה כרטיס ברכה ___ שלחה אותו למשפחה.",answer:"ואחר כך",en:"She wrote a greeting card and afterward sent it to the family."}
,
{sentence:"האריה אמר לזאב: אני תוקף אותך ___ אינך יודע לחלק שלל.",answer:"משום ש",en:"The lion said to the wolf: I am attacking you because you do not know how to divide the spoils."},
{sentence:"היום האישה עובדת יותר מאשר בעבר, ___ היא רצה לעבודה.",answer:"מפני ש",en:"Today the woman works more than in the past because she runs to work."},
{sentence:"התייר פחד מאוד. ___ הוא ביקש עזרה מאנשי החברה.",answer:"בגלל זה",en:"The tourist was very afraid. Because of this, he asked the company staff for help."},
{sentence:"הם חקרו אותו הרבה זמן, ___ הוא לא גילה להם דבר.",answer:"אך",en:"They questioned him for a long time, but he did not reveal anything to them."},
{sentence:"בעבר היה קשה להגיע לשם, ___ היום זה קל.",answer:"ואילו",en:"In the past it was difficult to get there, whereas today it is easy."}
],
matches:[
{prompt:"ספר",answer:"דבר שאפשר לקרוא"},
{prompt:"מורה",answer:"אדם שמלמד"},
{prompt:"תלמיד",answer:"אדם שלומד"},
{prompt:"כיסא",answer:"רהיט שיושבים עליו"},
{prompt:"מיטה",answer:"רהיט שישנים עליו"},
{prompt:"חלון",answer:"פתח בבית שרואים דרכו החוצה"},
{prompt:"דלת",answer:"דבר שפותחים כדי להיכנס"},
{prompt:"טלפון",answer:"מכשיר שמדברים איתו"},
{prompt:"מחשב",answer:"מכשיר שעובדים ולומדים איתו"},
{prompt:"משפחה",answer:"קבוצה של הורים וילדים"},
{prompt:"מבחן",answer:"דבר שבודק מה למדנו"},
{prompt:"מרפאה",answer:"מקום שבו רופא מטפל באנשים"},
{prompt:"פרופסור",answer:"אדם שמלמד וחוקר באוניברסיטה"},
{prompt:"כרטיס ברכה",answer:"כרטיס ששולחים בחג או באירוע"},
{prompt:"ילדות",answer:"השנים שבהן אדם היה ילד"},
{prompt:"געגועים",answer:"הרגשה כשרוצים להיות שוב עם אדם או במקום"},
{prompt:"זריחה",answer:"הזמן שבו השמש עולה"},
{prompt:"שקיעה",answer:"הזמן שבו השמש יורדת"},
{prompt:"אושר",answer:"הרגשה של שמחה גדולה"}
],
opposites:[
{prompt:"שמאל",answer:"ימין"},
{prompt:"צפון",answer:"דרום"},
{prompt:"מזרח",answer:"מערב"},
{prompt:"חדש",answer:"ישן"},
{prompt:"טוב",answer:"רע"},
{prompt:"גדול",answer:"קטן"},
{prompt:"חם",answer:"קר"},
{prompt:"מהר",answer:"לאט"},
{prompt:"פתוח",answer:"סגור"},
{prompt:"קרוב",answer:"רחוק"},
{prompt:"מוקדם",answer:"מאוחר"},
{prompt:"יש",answer:"אין"},
{prompt:"קצר",answer:"ארוך"},
{prompt:"ארוך",answer:"קצר"},
{prompt:"קל",answer:"קשה"},
{prompt:"קשה",answer:"קל"},
{prompt:"שמן",answer:"רזה"},
{prompt:"רזה",answer:"שמן"},
{prompt:"מצליח",answer:"נכשל"},
{prompt:"נכשל",answer:"מצליח"}
],
verbDefinitions:[
{he:"לכתוב",en:"to write"},{he:"לקרוא",en:"to read"},{he:"לאכול",en:"to eat"},{he:"לשתות",en:"to drink"},
{he:"ללכת",en:"to go / walk"},{he:"ללמוד",en:"to study / learn"},{he:"לעבוד",en:"to work"},{he:"לגור",en:"to live"},
{he:"לנסוע",en:"to travel / ride"},{he:"לקנות",en:"to buy"},{he:"לראות",en:"to see"},{he:"לעשות",en:"to do / make"},
{he:"להיכנס",en:"to enter"},{he:"לקום",en:"to get up"},{he:"לשלוח",en:"to send"},{he:"לפתוח",en:"to open"},
{he:"לעבור",en:"to pass / move"},{he:"לשאול",en:"to ask"},{he:"לרצות",en:"to want"},{he:"להצליח",en:"to succeed"},
{he:"להיכשל",en:"to fail"},{he:"להמציא",en:"to invent"},{he:"להשפיע",en:"to influence"},{he:"לכבד",en:"to honor"},
{he:"לשמוח",en:"to be happy"},{he:"לזכור",en:"to remember"},{he:"לבלות",en:"to spend time"},{he:"לחגוג",en:"to celebrate"},
{he:"להדליק",en:"to light / turn on"},{he:"ללבוש",en:"to wear"},{he:"להלביש",en:"to dress someone"},{he:"להתפלל",en:"to pray"},
{he:"לתלות",en:"to hang"},{he:"לסגור",en:"to close"},{he:"להסתכל",en:"to look at"},{he:"לברך",en:"to bless / greet"},
{he:"לסמס",en:"to text"},{he:"לעמוד",en:"to stand"},{he:"להשתמש",en:"to use"},{he:"לשמח",en:"to make someone happy"},
{he:"להתגעגע",en:"to miss / long for"},{he:"להכין",en:"to prepare"},{he:"להסביר",en:"to explain"},{he:"להסכים",en:"to agree"},
{he:"להחליט",en:"to decide"},{he:"לפטפט",en:"to chat"},{he:"להפריע",en:"to disturb / interrupt"},{he:"להמשיך",en:"to continue"},
{he:"להקשיב",en:"to listen"},{he:"להאמין",en:"to believe"},{he:"לפתור",en:"to solve"},{he:"להרוג",en:"to kill"},
{he:"לשמוע",en:"to hear"},{he:"לברוח",en:"to run away"},{he:"לחכות",en:"to wait"},{he:"לשתוק",en:"to be silent"},
{he:"להעדיף",en:"to prefer"},{he:"להאכיל",en:"to feed"},{he:"להעביר",en:"to pass / transfer"},{he:"להרגיש",en:"to feel"},
{he:"להזמין",en:"to invite"},{he:"להציע",en:"to suggest / propose"},{he:"לפרסם",en:"to publish"},{he:"לבדוק",en:"to check"},
{he:"לנוח",en:"to rest"},{he:"לבקש",en:"to request / ask for"},{he:"להבין",en:"to understand"},{he:"לחקור",en:"to research / investigate"},
{he:"לגלות",en:"to discover"},{he:"להרגיע",en:"to calm"},{he:"למנוע",en:"to prevent"},{he:"לסכן",en:"to endanger"},
{he:"לפזר",en:"to spread"},{he:"להחליף",en:"to change / replace"},{he:"לכבס",en:"to do laundry"},{he:"לשטוף",en:"to wash"},
{he:"לרחוץ",en:"to wash / bathe"},{he:"להגיש",en:"to serve"},{he:"לגהץ",en:"to iron"},{he:"לתקן",en:"to repair"},
{he:"להירדם",en:"to fall asleep"},{he:"לצאת",en:"to go out / leave"},{he:"לעסוק",en:"to engage in"},{he:"להספיק",en:"to have enough time"},
{he:"לזרוק",en:"to throw"},{he:"לשוחח",en:"to converse"},{he:"לשבת",en:"to sit"},{he:"לתת",en:"to give"},
{he:"לקחת",en:"to take"}
],
grammarQuestions:[
{cat:"הפועל להיות • עבר",prompt:"אני ___ בעיר אתמול.",answer:"הייתי",options:["הייתי","היה","הייתה","היו"],en:"I was in the city yesterday."},
{cat:"הפועל להיות • עבר",prompt:"הוא ___ בבית אתמול.",answer:"היה",options:["היה","הייתי","הייתה","היו"],en:"He was at home yesterday."},
{cat:"הפועל להיות • עבר",prompt:"היא ___ באוניברסיטה בבוקר.",answer:"הייתה",options:["הייתה","היה","היינו","היו"],en:"She was at the university in the morning."},
{cat:"הפועל להיות • עבר",prompt:"אנחנו ___ במסעדה בערב.",answer:"היינו",options:["היינו","הייתם","היו","הייתי"],en:"We were at the restaurant in the evening."},
{cat:"הפועל להיות • עבר",prompt:"הם ___ עייפים אחרי המבחן.",answer:"היו",options:["היו","היה","היינו","הייתה"],en:"They were tired after the exam."},
{cat:"צורת ההרגל",prompt:"כל יום הוא ___ הולך לשוק.",answer:"היה",options:["היה","הייתה","היו","הייתי"],en:"Every day he used to go to the market."},
{cat:"צורת ההרגל",prompt:"כל שנה הן ___ שולחות כרטיסי ברכה.",answer:"היו",options:["היו","היה","הייתה","היינו"],en:"Every year they used to send greeting cards."},
{cat:"התאמת שם ותואר",prompt:"בחרו את הצורה המתאימה: תלמיד ___",answer:"חדש",options:["חדש","חדשה","חדשים","חדשות"]},
{cat:"התאמת שם ותואר",prompt:"בחרו את הצורה המתאימה: תלמידה ___",answer:"חרוצה",options:["חרוצה","חרוץ","חרוצים","חרוצות"]},
{cat:"התאמת שם ותואר",prompt:"בחרו את הצורה המתאימה: טיול ___",answer:"קצר",options:["קצר","קצרה","קצרים","קצרות"]},
{cat:"התאמת שם ותואר",prompt:"בחרו את הצורה המתאימה: מרפאה ___",answer:"גדולה",options:["גדולה","גדול","גדולים","גדולות"]},
{cat:"יידוע שם ותואר",prompt:"השלימו: התלמיד ___",answer:"החדש",options:["החדש","חדש","החדשה","חדשה"]},
{cat:"יידוע שם ותואר",prompt:"השלימו: המרפאה ___",answer:"הגדולה",options:["הגדולה","גדולה","הגדול","גדול"]},
{cat:"משפט מטרה",prompt:"אני לומד הרבה ___ להצליח במבחן.",answer:"כדי",options:["כדי","אבל","או","כי"],en:"I study a lot in order to succeed on the exam."}
,
{cat:"כדי / כדי ש",prompt:"חברת הנסיעות מביאה את התייר אל האי ___ ללמד אותו לחיות לבד.",answer:"כדי",options:["כדי","כדי ש","אבל","מפני ש"],en:"The travel company brings the tourist to the island in order to teach him to live alone."},
{cat:"כדי / כדי ש",prompt:"חברת הנסיעות מביאה את התייר אל האי ___ הוא ילמד לחיות לבד.",answer:"כדי ש",options:["כדי ש","כדי","רק","אך"],en:"The travel company brings the tourist to the island so that he will learn to live alone."},
{cat:"כדי / כדי ש",prompt:"האישה הצעירה הלכה לקופת חולים ___ לדבר עם הרופא.",answer:"כדי",options:["כדי","כדי ש","לכן","אלא"],en:"The young woman went to the clinic in order to speak with the doctor."},
{cat:"כדי / כדי ש",prompt:"האישה הצעירה הלכה לקופת חולים ___ הרופא יבדוק אותה.",answer:"כדי ש",options:["כדי ש","כדי","כי","ואילו"],en:"The young woman went to the clinic so that the doctor would examine her."},
{cat:"כדי / כדי ש",prompt:"דני לומד באוניברסיטה ___ לשמח את אימו.",answer:"כדי",options:["כדי","כדי ש","משום ש","אך"],en:"Dani studies at the university in order to make his mother happy."},
{cat:"כדי / כדי ש",prompt:"דני לומד באוניברסיטה ___ אימו תשמח.",answer:"כדי ש",options:["כדי ש","כדי","מפני ש","רק"],en:"Dani studies at the university so that his mother will be happy."},
{cat:"צורת ההרגל",prompt:"כשהייתי ילד, אני ___ מבקר אצל סבא וסבתא כל יום שישי.",answer:"הייתי",options:["הייתי","היה","הייתה","היו"],en:"When I was a child, I used to visit Grandpa and Grandma every Friday."},
{cat:"צורת ההרגל",prompt:"בכל חג, סבא ___ נותן לנכדים ממתקים.",answer:"היה",options:["היה","הייתה","הייתי","היו"],en:"On every holiday, Grandpa used to give the grandchildren sweets."},
{cat:"צורת ההרגל",prompt:"בכל חג, סבתא ___ קוראת לנכדים סיפורים.",answer:"הייתה",options:["הייתה","היה","היו","היינו"],en:"On every holiday, Grandma used to read stories to the grandchildren."},
{cat:"צורת ההרגל",prompt:"לפני כל חג, בני הדודים ___ מציירים כרטיסי ברכה.",answer:"היו",options:["היו","היה","הייתה","הייתי"],en:"Before every holiday, the cousins used to draw greeting cards."},
{cat:"ציווי שלילי",prompt:"___ לרדיו בזמן השיעור.",answer:"אל תקשיב",options:["אל תקשיב","לא מקשיב","אל הקשבת","לא לשמוע"],en:"Do not listen to the radio during the lesson."},
{cat:"ציווי שלילי",prompt:"___ לכל הבטחה!",answer:"אל תאמיני",options:["אל תאמיני","לא מאמינה","אל האמנת","לא להאמין"],en:"Do not believe every promise!"},
{cat:"ציווי שלילי",prompt:"___ את כל האורות בבית!",answer:"אל תדליקו",options:["אל תדליקו","לא מדליקים","אל הדלקתם","לא להדליק"],en:"Do not turn on all the lights in the house!"},
{cat:"משפטי רצייה",prompt:"הוא רוצה שהספר ___ על הקוראים.",answer:"ישפיע",options:["ישפיע","משפיע","השפיע","להשפיע"],en:"He wants the book to influence the readers."},
{cat:"משפטי רצייה",prompt:"המורה דרשה שהתלמידים ___ לשיר.",answer:"יקשיבו",options:["יקשיבו","מקשיבים","הקשיבו","להקשיב"],en:"The teacher demanded that the students listen to the song."},
{cat:"משפטי רצייה",prompt:"אני מקווה שהספר שלי ___.",answer:"יצליח",options:["יצליח","מצליח","הצליח","להצליח"],en:"I hope that my book will succeed."}

],
classVerbQuestions:[
{cat:"פעלים מהשיעור • עבר",prompt:"עבר • אני • להמציא",answer:"המצאתי",options:["המצאתי","המציא","המציאה","המציאו"]},
{cat:"פעלים מהשיעור • עבר",prompt:"עבר • הוא • להמציא",answer:"המציא",options:["המציא","המצאתי","ממציא","ימציא"]},
{cat:"פעלים מהשיעור • עבר",prompt:"עבר • הם • להמציא",answer:"המציאו",options:["המציאו","המציא","ממציאים","ימציאו"]},
{cat:"פעלים מהשיעור • להזמין",prompt:"עתיד • אני • להזמין",answer:"אזמין",options:["אזמין","הזמנתי","מזמינה","יזמין"]},
{cat:"פעלים מהשיעור • להתאים",prompt:"עתיד • אתה • להתאים",answer:"תתאים",options:["תתאים","התאמת","מתאים","יתאים"]},
{cat:"פעלים מהשיעור • להרגיש",prompt:"עבר • את • להרגיש",answer:"הרגשת",options:["הרגשת","מרגישה","תרגישי","הרגיש"]},
{cat:"פעלים מהשיעור • להשפיע",prompt:"עתיד • הוא • להשפיע",answer:"ישפיע",options:["ישפיע","השפיע","משפיע","תשפיע"]},
{cat:"פעלים מהשיעור • להדליק",prompt:"עבר • היא • להדליק",answer:"הדליקה",options:["הדליקה","מדליקה","תדליק","הדליק"]},
{cat:"פעלים מהשיעור • להצליח",prompt:"עתיד • אנחנו • להצליח",answer:"נצליח",options:["נצליח","הצלחנו","מצליחים","יצליחו"]},
{cat:"פעלים מהשיעור • להעביר",prompt:"עתיד • אתן • להעביר",answer:"תעבירו",options:["תעבירו","העברתן","מעבירות","יעבירו"]},
{cat:"פעלים מהשיעור • לשבת",prompt:"עתיד • אני • לשבת",answer:"אשב",options:["אשב","ישבתי","יושב","נשב"]},
{cat:"פעלים מהשיעור • לשבת",prompt:"עתיד • את • לשבת",answer:"תשבי",options:["תשבי","תשב","ישבה","יושבת"]},
{cat:"פעלים מהשיעור • לשבת",prompt:"עתיד • אנחנו • לשבת",answer:"נשב",options:["נשב","אשב","תשבו","ישבנו"]},
{cat:"פעלים מהשיעור • לתת",prompt:"עתיד • אני • לתת",answer:"אתן",options:["אתן","נתתי","נותן","ניתן"]},
{cat:"פעלים מהשיעור • לתת",prompt:"עתיד • את • לתת",answer:"תתני",options:["תתני","תיתן","נתת","נותנת"]},
{cat:"פעלים מהשיעור • לקחת",prompt:"עתיד • אני • לקחת",answer:"אקח",options:["אקח","לקחתי","לוקח","ניקח"]},
{cat:"פעלים מהשיעור • לקחת",prompt:"עתיד • אתם • לקחת",answer:"תיקחו",options:["תיקחו","לקחתם","לוקחים","ייקחו"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להפסיק?",answer:"הפסקה",options:["הפסקה","הקשבה","הפרעה","החלטה"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להקשיב?",answer:"הקשבה",options:["הקשבה","הפסקה","אמונה","הפתעה"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להפריע?",answer:"הפרעה",options:["הפרעה","הסבר","החלטה","הקשבה"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להאמין?",answer:"אמונה",options:["אמונה","החלטה","הפתעה","הפסקה"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להסביר?",answer:"הסבר",options:["הסבר","הפרעה","אמונה","החלטה"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להחליט?",answer:"החלטה",options:["החלטה","הפתעה","הקשבה","הסבר"]},
{cat:"שם הפעולה מהשיעור",prompt:"מה שם הפעולה של להפתיע?",answer:"הפתעה",options:["הפתעה","הפסקה","הפרעה","אמונה"]}
]};